=== clairbond/lmsgi-asir11-05/XML/UT5/ORDENADORES /xsd/xsd-ordenadores.xsd
<?xml version='1.0' encoding='UTF-8'?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
targetNamespace='http://www.iescierva.net'
xmlns='http://www.iescierva.net' elementFormDefault='qualified'>


<xs:element name='ordenadores'>
  <xs:complexType>
    <xs:sequence>
		<xs:element name='ordenador' minOccurs='1' maxOccurs='unbounded'>
  			<xs:complexType>
      			<xs:sequence>
      				<xs:choice minOccurs='0' maxOccurs='10'>
        				<xs:element name='hardware' type='definición' />
     					<xs:element name='software' type='definición' />
      				</xs:choice>
    			</xs:sequence>
    			<xs:attribute name='tipo' type='definición' />
  			</xs:complexType>
  		</xs:element>	
			<xs:element name='hardware' minOccurs='1' maxOccurs='unbounded'>
  				<xs:complexType>
      				<xs:sequence>
      					<xs:choice minOccurs='0' maxOccurs='10'>
        					<xs:element name='placa_base' type='definición' />
     						<xs:element name='cpu' type='definición'/>
     						<xs:element name='memoria_ram' type='definición' />
     						<xs:element name='pci' type='definición' />
     						<xs:element name='unidad_cd' type='definición' />
      					</xs:choice>
    				</xs:sequence>
  				</xs:complexType>
			</xs:element>

			
					<xs:element name='placa_base' minOccurs='1' maxOccurs='unbounded'>
  						<xs:complexType>
      						<xs:sequence>
      							<xs:choice minOccurs='0' maxOccurs='10' />
      						</xs:sequence>
    						<xs:attribute name='marca' type='definición' />
    						<xs:attribute name='modelo' type='definición' />
    						<xs:attribute name='cpu' type='definición' />
    						<xs:attribute name='chipset' type='definición' />
  						</xs:complexType>
					</xs:element>

					<xs:element name='cpu' minOccurs='1' maxOccurs='unbounded'>
  						<xs:complexType>
      						<xs:sequence>
      							<xs:choice minOccurs='0' maxOccurs='10' />
    						</xs:sequence>
    						<xs:attribute name='marca' type='definición' />
    						<xs:attribute name='modelo' type='definición' />
   							<xs:attribute name='frecuencia' type='definición' />
    						<xs:attribute name='número_nucleos' type='definición' />
  						</xs:complexType>
					</xs:element>

					<xs:element name='pci' minOccurs='1' maxOccurs='unbounded'>
  						<xs:complexType>
      						<xs:sequence>
      							<xs:choice minOccurs='0' maxOccurs='10'>
       								<xs:element name='tarjeta_grafica' type='definición' />
									<xs:element name='tarjeta_red' type='definición' />
     								<xs:element name='tarjeta_sonido' type='definición' />
    							</xs:choice>
    						</xs:sequence>
    						<xs:attribute name='marca' type='definición' />
    						<xs:attribute name='modelo' type='definición' />
 							</xs:complexType>
					</xs:element>



					<xs:element name='memoria_ram' minOccurs='1' maxOccurs='unbounded'>
  						<xs:complexType>
     						<xs:sequence>
      							<xs:choice minOccurs='0' maxOccurs='10' />
      						</xs:sequence>
   							 <xs:attribute name='marca' type='definición' />
   							 <xs:attribute name='modelo' type='definición' />
  							 <xs:attribute name='numero_ranuras' type='definición' />
  							 <xs:attribute name='tipo' type='definición' />
  							 <xs:attribute name='tamaño_modulos' type='definición' />
  						</xs:complexType>
					</xs:element>

					<xs:element name='unidad_cd' minOccurs='1' maxOccurs='unbounded'>
  						<xs:complexType>
      						<xs:sequence>
      							<xs:choice minOccurs='0' maxOccurs='10' />
    						</xs:sequence>
    					<xs:attribute name='marca' type='definición' />
   						<xs:attribute name='modelo' type='definición' />
    					<xs:attribute name='numero' type='definición' />
    					<xs:attribute name='velocidad' type='definición' />
  						</xs:complexType>
					</xs:element>



					<xs:element name='software' minOccurs='1' maxOccurs='unbounded'>
  						<xs:complexType>
      						<xs:sequence>
      							<xs:choice minOccurs='0' maxOccurs='10'>
        							<xs:element name='BIOS' type='definición' />
     								<xs:element name='sistema_operativo' type='definición' />
      							</xs:choice>
   							 </xs:sequence>
  						</xs:complexType>
					</xs:element>

			</xs:sequence>
  	</xs:complexType>
</xs:element>

    

<!-- Definiciones de tipos personalizados -->


<xs:simpleType name='email'>
    <xs:restriction base='xs:string'>
     <xs:pattern value='[a-zA-Z_.-][a-zA-Z0-9_.-]*@[a-zA-Z0-9_.-]+'/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name='teléfono'>
  <xs:restriction base='xs:string'>
    <xs:pattern value='[+0-9 _.-]{3,20}'/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name='definición'>
  <xs:restriction base='xs:string'>
    <xs:pattern value='[a-zA-ZáéíóúÁÉÍÓÚüÜçÇ0-9 -]{1,20}'/>
  </xs:restriction>
</xs:simpleType>

<xs:simpleType name='fecha'>
  <xs:restriction base='xs:date'>
    <xs:pattern value='[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}'/>    		
  </xs:restriction>
</xs:simpleType> 


</xs:schema>

=== clairbond/lmsgi-asir11-05/XML/UT5/ORDENADORES /ordenadores_con_xsd.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>

<ordenadores
xmlns='http://www.iescierva.net'
xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:schemaLocation='xsd/xsd-ordenadores.xsd'>


	<ordenador tipo='sobremesa'>
		<hardware>
			<placa_base marca='ASUS' modelo='P5G41T-M LE' cpu='Procesadores Intel Socket 775' chipset='	G41 / ICH7' />
			<cpu marca='Intel' modelo='Celeron E3400 ' frecuencia='2,6 GHz' número_nucleos='2' />	
			<pci>
				<tarjeta_grafica marca='Shapphire Radeon' modelo='HD 6770 Vapor-X' />
				<tarjeta_red marca='TP-Link' modelo='TF-3239DL' />
				<tarjeta_sonido marca='Trust' modelo='5.1 Surround Soundcard SC-5100 ' />		
			</pci>
			<memoria_ram marca='Kingston' modelo='ValueRAM' numero_ranuras='4' tipo='DDR3' tamaño_modulos='2G' />
			<unidad_cd marca='LG' modelo='LG3452M' numero='1' velocidad='52x' />
		</hardware>
		
		<software>
			<BIOS>Phoenix Bios</BIOS>
			<sistema_operativo>Ubuntu 11.04</sistema_operativo>
		</software>
	</ordenador>		
</ordenadores>
