=== clairbond/lmsgi-asir11-05/XML/UT5/023-datos personales.dtd
<?xml version='1.0' encoding='utf-8'?>


<!ELEMENT listado (datos+)>
<!ELEMENT datos (nombre+, dirección?, (móvil|email)*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT dirección (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT móvil (#PCDATA)>

<!ENTITY ra "Raúl Leal">

=== clairbond/lmsgi-asir11-05/XML/UT5/023-datos personales.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>

<!DOCTYPE listado SYSTEM "023-datos personales.dtd">

<listado>
	<datos>
		<nombre>Juanito</nombre>
		<dirección>Mi casa</dirección>
		<email>juanito@gmail.com</email>
		<email>juanito.privado@yahoo.com</email>
		<móvil>666111777</móvil>
		<email>pruebas@gmail.com</email>
	</datos>
	
	<datos>
		<nombre>Lola</nombre>
		<dirección>Plaza Mayor</dirección>
	</datos>
	
	<datos>
		<nombre>&ra;</nombre>
	</datos> 
</listado>
