=== clairbond/lmsgi-asir11-05/XML/UT5/ORDENADORES/dtd/ordenadores.dtd
<?xml version='1.0' encoding='utf-8'?>

<!ELEMENT ordenadores (ordenador*)>

<!ELEMENT ordenador (sobremesa*,portatil*)>

<!ELEMENT sobremesa (hardware*, software*)>

<!ELEMENT hardware (procesador*, monitor*, teclado*, tarjeta_red*, tarjeta_grafica*)>

<!ELEMENT procesador (#PCDATA)>
<!ELEMENT monitor (#PCDATA)>
<!ELEMENT teclado (#PCDATA)>
<!ELEMENT tarjeta_red (#PCDATA)>
<!ELEMENT tarjeta_grafica (#PCDATA)>

<!ELEMENT software ( bios*, sisoperativo*)>
<!ELEMENT bios (#PCDATA)>
<!ELEMENT sisoperativo (#PCDATA)>

<!ATTLIST sobremesa
marca CDATA #REQUIRED
memoria CDATA #REQUIRED
velocidad CDATA #REQUIRED
n_nucleos CDATA #REQUIRED
>

<!ELEMENT portatil (hardware*, software*)>



<!ATTLIST portatil
marca CDATA #REQUIRED
memoria CDATA #REQUIRED
velocidad CDATA #REQUIRED
n_nucleos CDATA #REQUIRED
>

=== clairbond/lmsgi-asir11-05/XML/UT5/ORDENADORES/ordenadores_con_dtd.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>

<!DOCTYPE ordenadores.dtd SYSTEM "dtd/ordenadores.dtd">

<ordenadores>
	<ordenador>
		<sobremesa marca='hp' memoria='4Gb' velocidad='2.2Ghz' n_nucleos='4'>

			<hardware>
				<procesador>Intel Core i5-2537M</procesador>
				<monitor>samsung-22p350</monitor>
				<teclado>inhalambrico</teclado>
				<tarjeta_red>TP-Link TF-3239DL</tarjeta_red>
				<tarjeta_grafica>nvidia_GeForce GTX 590</tarjeta_grafica>
			</hardware>
			<software>
				<bios></bios>
				<sisoperativo>ubuntu 11.04</sisoperativo>
			</software>
		</sobremesa>

		<portatil marca='dell' memoria='8Gb' velocidad='2.6Ghz' n_nucleos='8'>
			<hardware>
				<procesador>intel Core i7-2960XM</procesador>
				<monitor>17 pulgadas</monitor>
				<teclado>normal</teclado>
				<tarjeta_red>LG-Ericsson Smc 1255TX-2</tarjeta_red>
				<tarjeta_grafica>GeForce GTX 560 Ti</tarjeta_grafica>
			</hardware>
			<software>
				<bios></bios>
				<sisoperativo>windows 7</sisoperativo>
			</software>
		</portatil>
	</ordenador>
</ordenadores>
