=== clairbond/lmsgi-asir11-05/XML/UT5/xsd/xsd-personas.xsd
<?xml version='1.0' encoding='utf-8'?>

<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema'
targetNamespace='http://www.iescierva.net'
xmlns='http://www.iescierva.net' elementFormDefault="qualified">

<xs:element name='personas'>
	<xs:complexType>
    	<xs:sequence>
			<xs:element name='persona' minOccurs='1' maxOccurs='unbounded'>
  				<xs:complexType>
    				<xs:sequence>
    					<xs:element name='nombre'>
    						<xs:simpleType>
    							<xs:restriction base='xs:string'>
									<xs:pattern value='[a-zA-ZáéíóúÁÉÍÓÚüÜçÇ ]{1,20}'/>    		
    							</xs:restriction>
 	   						</xs:simpleType>   	
    					</xs:element>
    		
						<xs:element name='apellidos'>
							<xs:simpleType>
    							<xs:restriction base='xs:string'>
									<xs:pattern value='[a-zA-ZáéíóúÁÉÍÓÚüÜçÇ -]{1,20}'/>    		
    							</xs:restriction>
    						</xs:simpleType>   	
    					</xs:element>
		
      					<xs:element name='fnac'>
							<xs:simpleType>
    							<xs:restriction base='xs:date'>
									<xs:pattern value='[0-9]{1,4}-[0-9]{1,2}-[0-9]{1,2}'/>    		
    							</xs:restriction>
    						</xs:simpleType>   	
    					</xs:element>
      	
      					<xs:element name='email'>
							<xs:simpleType>
    							<xs:restriction base='xs:string'>
									<xs:pattern value='[a-zA-Z._][a-zA-Z._0-9]*\@[a-zA-Z0-9][a-zA-Z0-0.-]*'/>    		
    							</xs:restriction>
    						</xs:simpleType>   	
    					</xs:element>
    	
    				</xs:sequence>
  				</xs:complexType>
			</xs:element>
		</xs:sequence>
  	</xs:complexType>		
</xs:element>

</xs:schema>

=== clairbond/lmsgi-asir11-05/XML/UT5/11-personas.xml
<?xml version='1.0' encoding='utf-8' standalone='no'?>

<personas
xmlns='http://www.iescierva.net'
xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
xsi:schemaLocation='http://www.iescierva.net xsd/xsd-personas.xsd'>

	<persona>
		<nombre>Luis</nombre>
		<apellidos>Hernández  Martínez</apellidos>
		<fnac>2000-01-03</fnac>
		<email>luis@gmail.com</email>
	</persona>
	
 	<persona>
		<nombre>Ginés</nombre>
		<apellidos>García García</apellidos>
		<fnac>1980-03-09</fnac>
		<email>ggg@gmail.com</email>
	</persona>
	
	<persona>
		<nombre>Pepe</nombre>
		<apellidos>Nieto Suarez</apellidos>
		<fnac>1990-04-03</fnac>
		<email>pepe@gmail.com</email>
	</persona> 


</personas>
